Writeoff wrapper
centrifuge/tinlake pull request #613
Opened 2022-06-24 21:55 UTC by AStox

2022-10-25 17:45 UTC, AStox commented on src/borrower/wrappers/test/writeoffWrapper.t.sol
> +        writeoffWrapper.writeOff(1, address(pile), address(navFeed));
I can't seem to find an dapp tools equivalent for `vm.expectRevert`. This might have to wait until I swap Tinlake over to foundry

2022-10-26 17:53 UTC, ilinzweilin requested changes

2022-10-26 17:53 UTC, ilinzweilin commented on src/borrower/wrappers/writeOffWrapper.sol
> +        writeOffRates[address(0x0168e7999318a6c2393c2Eb19A5Da4aB9d715173)] = 1000;  // FactorChain 1
that's the pile fab address:
PILE: `0x99D0333f97432fdEfA25B7634520d505e58B131B`

2022-10-26 17:53 UTC, ilinzweilin commented on src/borrower/wrappers/writeOffWrapper.sol
> +        writeOffRates[address(0xAAEaCfcCc3d3249f125Ba0644495560309C266cB)] = 1001;  // Pezesha 1
Pezesha already exists

2022-10-26 17:53 UTC, ilinzweilin commented on src/borrower/wrappers/writeOffWrapper.sol
> +        writeOffRates[address(0x3fC72dA5545E2AB6202D81fbEb1C8273Be95068C)] = 1001;  // ConsolFreight 4
CS4 should have write off group 1000

2022-10-26 17:53 UTC, ilinzweilin commented on src/borrower/wrappers/writeOffWrapper.sol
> +
Peoples-1 missing

2022-11-07 15:06 UTC, offerijns approved these changes

2022-11-07 15:07 UTC, merged