docs: added NatSpec comments for borrower contracts
centrifuge/tinlake pull request #621
Opened 2022-11-09 10:23 UTC by xmxanuel

I started to add `NatSpec` comments for the borrower contracts.
It is a commonly used standard nowadays for Solidity.

Writing those comments is surprisingly easy together with Github Copilot. 

For me, it is also an excellent way to refresh my understanding of the codebase again.

2022-11-18 19:10 UTC, AStox requested changes
Just a few more typos and nit picks

2022-11-18 19:10 UTC, AStox commented on src/borrower/pile.sol
> +    /// @notice accrue needs to be called before any debt amounts are modified by an external component
```suggestion
    /// @notice calls drip on the given loan
    /// @dev accrue needs to be called before any debt amounts are modified by an external component
```

2022-11-18 19:10 UTC, AStox commented on src/borrower/shelf.sol
> +    /// @notice withdraw transfers the acutal currency to the borrower account
```suggestion
    /// @notice withdraw transfers the actual currency to the borrower account
```

2022-11-18 19:10 UTC, AStox commented on src/borrower/shelf.sol
> +    /// requires an issued loan
```suggestion
    /// @dev requires an issued loan
```

2022-11-18 19:10 UTC, AStox commented on src/borrower/shelf.sol
> +    /// requires zero debt or 100% write off
```suggestion
    /// @dev requires zero debt or 100% write off
```

2022-11-18 19:10 UTC, AStox commented on src/borrower/wrappers/writeOffWrapper.sol
> +    /// @notice writes of an overdue loan
```suggestion
    /// @notice writes off an overdue loan
```

2022-11-21 04:43 UTC, AStox submitted a review, later dismissed
Looks great!

2022-11-22 14:24 UTC, offerijns approved these changes

2022-11-22 16:00 UTC, AStox approved these changes
LGTM

2022-11-22 16:13 UTC, merged