chore: natSpec for lender contracts
centrifuge/tinlake pull request #624
Opened 2022-11-14 17:17 UTC by xmxanuel

- adding NAT spec to the lender contracts
- in some cases the function signature has been modified

2022-11-17 22:28 UTC, AStox requested changes
Nice work! Just a few typos and re-wordings

2022-11-17 22:28 UTC, AStox commented on src/lender/operator.sol
> +/// @notice the operator contract is the entry point for a tranche contracts
```suggestion
/// @notice the operator contract is the entry point for a tranche contract
```

2022-11-17 22:28 UTC, AStox commented on src/lender/token/memberlist.sol
> +/// @notice mantains a authorized list of members
```suggestion
/// @notice maintains an authorized list of members
```

2022-11-17 22:28 UTC, AStox commented on src/lender/token/memberlist.sol
> +    /// minimum 7 day since block.timestamp
```suggestion
    /// minimum 7 days since block.timestamp
```

2022-11-17 22:28 UTC, AStox commented on src/lender/token/memberlist.sol
> +    /// @param validUntil the timestamp until the user is a member
```suggestion
    /// @param validUntil the timestamp for when the user's member status ends
```

2022-11-17 22:28 UTC, AStox commented on src/lender/token/restricted.sol
> +/// @notice RestictedERC20 token only mebmber with a valid (not expired) membership should be allowed to receive tokens
```suggestion
/// @notice RestrictedERC20 token only member with a valid (not expired) membership should be allowed to receive tokens
```

2022-11-17 22:28 UTC, AStox commented on src/lender/coordinator.sol
> +/// @notice The EpochCoordinator keeps track of the epochs and execute epochs them.
```suggestion
/// @notice The EpochCoordinator keeps track of the epochs and executes them.
```

2022-11-17 22:28 UTC, AStox commented on src/lender/coordinator.sol
> +    /// returns the difference between two values as absolute value
```suggestion
    /// @notice returns the difference between two values as absolute value
```

2022-11-17 22:28 UTC, AStox commented on src/lender/coordinator.sol
> +    /// for gas optimization if both values are equal 1 is returned to avoid a special zero case in other methods
```suggestion
    /// for gas optimization if both values are equal, 1 is returned to avoid a special zero case in other methods
```

2022-11-17 22:28 UTC, AStox commented on src/lender/tranche.sol
> +    /// @notice supplyOrder function can be used to place or revoke an supply
```suggestion
    /// @notice supplyOrder function can be used to place or revoke a supply
```

2022-11-17 22:28 UTC, AStox commented on src/lender/tranche.sol
> +    /// @notice view function to calculat the current disburse amount for a user
```suggestion
    /// @notice view function to calculate the current disburse amount for a user
```

2022-11-17 22:28 UTC, AStox commented on src/lender/tranche.sol
> +    /// @notice  calculates the current disburse of a user starting from the ordered epoch until endEpoch
```suggestion
    /// @notice calculates the current disburse of a user starting from the ordered epoch until endEpoch
```

2022-11-17 22:28 UTC, AStox commented on src/lender/tranche.sol
> +    /// if the amount is higher than the balance of the contract, there is no revert
```suggestion
    /// @dev if the amount is higher than the balance of the contract, there is no revert
```

2022-11-17 22:28 UTC, AStox commented on src/lender/tranche.sol
> +    /// if the the amount is higher than the maxium the maximum is burned
```suggestion
    /// @dev if the the amount is higher than the maximum, the maximum is burned
```

2022-11-17 22:28 UTC, AStox commented on src/lender/tranche.sol
> +    /// In such a case the currency is not immediatly available in the reserve and needs to be first
```suggestion
    /// In such a case the currency is not immediately available in the reserve and needs to be first
```

2022-11-17 22:28 UTC, AStox commented on src/root.sol
> +    /// @notice sets two deployer dependcies with no admins.
```suggestion
    /// @notice sets two deployer dependencies with no admins.
```

2022-11-17 22:28 UTC, AStox commented on src/root.sol
> +    /// @notice sets two deployer dependcies with no admins and no adapter
```suggestion
    /// @notice sets two deployer dependencies with no admins and no adapter
```

2022-11-18 09:57 UTC, xmxanuel commented
@AStox thanks for reading all the comments carefully.  I guess the task was a bit repetitive, sorry for all the typos.

2022-11-18 12:24 UTC, offerijns approved these changes

2022-11-21 04:42 UTC, AStox approved these changes

2022-11-21 14:50 UTC, merged